name: lnu_navigator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-96.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0-dev.3
  freezed_annotation: ^0.15.0
  panorama: ^0.4.1
  provider: ^6.0.3
  uuid: 3.0.6
  firebase_storage: ^11.0.4
  flutter_colorpicker: ^1.0.3
  cached_network_image: ^3.2.3
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^0.15.1+1
  build_runner: ^2.1.5

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/buildings/
    - assets/dormitory_3/
    - assets/dormitory_3/6/
    - assets/dormitory_3/7/
  uses-material-design: true
